### ISSUE TITLE
Errors when using with latest Ink-Unity-Integration build

### ISSUE THREAD

**Issue by ladyisidore** [abroder/blot#1]
When I import Script.cs into my project, which is using the latest version of Ink-Unity-Built, I get the following errors:

> `Assets/Script.cs(24,35): error CS0117: 'Ink.Runtime.Story' does not contain a definition for 'CreateWithJson'`
> `Assets/Script.cs(49,89): error CS1061: Type 'Ink.Runtime.Choice' does not contain a definition for 'choiceText' and no extension method 'choiceText' of type 'Ink.Runtime.Choice' could be found (are you missing a using directive or an assembly reference?)`

Any idea what's going on?

**Comment by abroder** [comment]
Haven't updated this in a while, but Ink's been updated a lot; just pushed a new version that uses the latest version of Ink, so it should work now!
