### ISSUE TITLE
Text formatting?

### ISSUE THREAD

**Issue by ladyisidore** [abroder/blot#2]
I'm atrociously new to Unity, so I'm sorry if this is a very obvious question, but how do I confine the text to a certain width and make it scroll, rather than make each snippet replace the previous one wholesale?

If this isn't the place to ask for such help, feel free to close the topic!

**Comment by abroder** [comment]
Hi @isakgrozny! This project is supposed to be a minimum viable UI to get started playing with Inkle in Unity. I don't really have much Unity knowledge so I can't really help with this. Sorry!
